## This notebook is for implementing numpy array

In [2]:
print("Hello People of the World")

Hello People of the World


In [3]:
import numpy as np

In [4]:
np.random.seed(323)

In [5]:
num1 = 10

In [6]:
# Generate 10 random numbers
my_vec1 = np.random.random(num1)

In [7]:
print(my_vec1)

[0.97338848 0.11034681 0.90384982 0.87548058 0.97599424 0.57894945
 0.99898921 0.6440637  0.13576663 0.96096404]


In [8]:
type(my_vec1)

numpy.ndarray

In [9]:
my_vec1.shape

(10,)

In [12]:
my_vec2 = np.random.random(num1)

In [13]:
print(my_vec2)

[0.98386919 0.78694757 0.78081596 0.19752816 0.73085947 0.47909419
 0.002589   0.11402797 0.29617625 0.05994821]


### Vectorized way of multiplication

In [14]:
result1 = np.dot(my_vec1, my_vec2)

In [15]:
print(result1)

3.0877290360384206


In [16]:
result0 = 0

for x in range(num1):
    result0 += my_vec1[x] * my_vec2[x]

print(result0)    

3.087729036038421


In [17]:
# Transforming the list into the numpy array and also back into the list is also possible
list1 = [3, 1, 4, 2, 6, 8, 7, 9]

In [18]:
type(list1)

list

In [19]:
nparray1 = np.array(list1)

In [20]:
type(nparray1)

numpy.ndarray

In [22]:
list2 = list(nparray1)

In [24]:
type(list2)


list

In [26]:
# Trying the functions on list to check if the usual append function of list will work on this transformed list or not.
list2.append(13)

In [27]:
print(list2)

[np.int64(3), np.int64(1), np.int64(4), np.int64(2), np.int64(6), np.int64(8), np.int64(7), np.int64(9), 13]


In [28]:
for x in list2:
    print(x)

3
1
4
2
6
8
7
9
13


In [25]:
print(list2)


[np.int64(3), np.int64(1), np.int64(4), np.int64(2), np.int64(6), np.int64(8), np.int64(7), np.int64(9)]


In [29]:
list2.remove(13)

In [30]:
for x in list2:
    print(x)

3
1
4
2
6
8
7
9


---

## Matrix

In [35]:
mymat1 = np.asmatrix('3, 2, 1;4, 1, 5;4, 1, 7')

In [36]:
print(mymat1)

[[3 2 1]
 [4 1 5]
 [4 1 7]]


In [37]:
type(mymat1)

numpy.matrix

In [38]:
# Transpose
mymat1.T

matrix([[3, 4, 4],
        [2, 1, 1],
        [1, 5, 7]])

In [39]:
mymat_inv = np.linalg.inv(mymat1)

In [40]:
print(mymat_inv)

[[-0.2  1.3 -0.9]
 [ 0.8 -1.7  1.1]
 [ 0.  -0.5  0.5]]


In [41]:
# Determinant of a matrix
mymat_det = np.linalg.det(mymat1)

In [42]:
print(mymat_det)

-9.999999999999998


---

### Multi dimentional array

In [43]:
my_2d_array1 = np.array([(2, 1, 5),(4, 1, 5),(2, 7, 6)])

In [45]:
print(my_2d_array1)

[[2 1 5]
 [4 1 5]
 [2 7 6]]


In [46]:
type(my_2d_array1)

numpy.ndarray

In [47]:
# Implementing transpose function which is a part of matrix on the above numpy array.

my_2d_array1.T

array([[2, 4, 2],
       [1, 1, 7],
       [5, 5, 6]])

In [48]:
np.linalg.inv(my_2d_array1)

array([[-5.00000000e-01,  5.00000000e-01,  3.46944695e-18],
       [-2.41379310e-01,  3.44827586e-02,  1.72413793e-01],
       [ 4.48275862e-01, -2.06896552e-01, -3.44827586e-02]])

In [49]:
np.linalg.det(my_2d_array1)

np.float64(57.999999999999986)

In [50]:
my_2d_array1.shape

(3, 3)

In [51]:
my_2d_array1.ndim

2

In [52]:
# We are trying to create further dimension of the numpy array.

my_3d_array1 = np.array([[(2, 1, 4),(4, 2, 7)],[(5, 1, 6),(6, 4, 8)]])

In [53]:
print(my_3d_array1)

[[[2 1 4]
  [4 2 7]]

 [[5 1 6]
  [6 4 8]]]


In [54]:
my_3d_array1.shape

(2, 2, 3)

In [55]:
my_3d_array1.size

12

In [56]:
#### Matrix or numpy array full of 1's

one_mat1 = np.ones((4, 5))

In [57]:
one_mat1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
iden_mat1 = np.eye(6)

In [59]:
iden_mat1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

---

### Using numpy array, we can generate sequences as well:


In [61]:
data1 = np.arange(1, 100, 5)

In [62]:
print(data1)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [63]:
data2 = np.linspace(1, 20, 40)

In [64]:
print(data2)

[ 1.          1.48717949  1.97435897  2.46153846  2.94871795  3.43589744
  3.92307692  4.41025641  4.8974359   5.38461538  5.87179487  6.35897436
  6.84615385  7.33333333  7.82051282  8.30769231  8.79487179  9.28205128
  9.76923077 10.25641026 10.74358974 11.23076923 11.71794872 12.20512821
 12.69230769 13.17948718 13.66666667 14.15384615 14.64102564 15.12820513
 15.61538462 16.1025641  16.58974359 17.07692308 17.56410256 18.05128205
 18.53846154 19.02564103 19.51282051 20.        ]


In [65]:
# Reshaping is also allowed in numpy

data3 = np.arange(20)

In [66]:
data3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
newarray3 = data3.reshape(5, 2, 2)

In [71]:
newarray3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

Below code is generating the random numbers in such a manner that `mean ---> 0` and `std ---> 1`

In [88]:
# Normally distributed random numbers can also be generated
array3_norm = np.random.randn(100000000)

In [89]:
array3_norm

array([-0.26872016, -1.35982093,  0.47030658, ...,  1.06602364,
       -0.78290868, -0.5411413 ], shape=(100000000,))

In [90]:
np.std(array3_norm)

np.float64(1.0000148274013172)

In [91]:
np.mean(array3_norm)

np.float64(-0.00012083859959927234)

In [96]:
# we can generate random integers as well
num_int1 = np.random.randint(10, 50)

In [97]:
num_int1

30

In [98]:
# 3rd argument defines how many integers to generate 
num_int2 = np.random.randint(10, 50, 10)

In [99]:
num_int2

array([23, 12, 37, 33, 36, 39, 38, 39, 38, 25], dtype=int32)